### PR TITLE
Remove debug output

### PR DESCRIPTION
**Pull request by kudos**
Also added repository url to `package.json` to stop `npm` complaining.

### CODE REVIEW

**Comment by kudos** [comment]
@christkv bump.

**Comment by christkv** [comment]
I'm currently working on 2.0.36 which will have promises merged into it :) so this branch will nolonger be needed

**Comment by kudos** [comment]
I look forward to it :+1: Can I get you to release this change in the meantime?

**Comment by christkv** [comment]
published 1.0.3

**Pull request merged**
